### ISSUE TITLE
Change widget design: add colors

### ISSUE THREAD

**Issue by DragonCat4012** [HanashiDev/Haltestellenmonitor-v3#34]
- [ ] make tile bigger
- [ ] add yolor to title
- [x] add color for each departure
- [ ]  Add this design to the standard views too (@t0mbrn )

![grafik](https://github.com/HanashiDev/Haltestellenmonitor-v3/assets/68660034/7ef3ca10-1e9d-45fb-aa1c-9e5bd9e79e23)

**Comment by t0mbrn** [comment]
- [ ] Add this design to the standard views too

**Comment by DragonCat4012** [comment]
![grafik](https://github.com/HanashiDev/Haltestellenmonitor-v3/assets/68660034/619592b0-5527-4e56-b9e9-a369053be648)

**Comment by t0mbrn** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/68660034/320783395-619592b0-5527-4e56-b9e9-a369053be648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTMxMTgsIm5iZiI6MTcxMjY1MjgxOCwicGF0aCI6Ii82ODY2MDAzNC8zMjA3ODMzOTUtNjE5NTkyYjAtNTUyNy00ZTU2LWI5ZTktYTM2OTA1M2JlNjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA4NTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MWY1MjY4OTdhODNlNzVjYzk3MmFmY2JkOTAzN2Y4ZjAzOTU0MDc5Mjc2MDRhMGQwNDk2NmQxODExNDEwMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YFEAwbrQNTpgxiyeSi36z8JUxCH_YgY7pYcdpnCjaX0)

hmm die Farben sind noch nicht wirklich harmonisch oder?

**Comment by DragonCat4012** [comment]
ja sind halt die standard swiftui farebn ^^" dunno mit gleben hintergrund sowieso so ne sache xd kann aber auhc cutsom colors für machen an sich
